apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

configMapGenerator:
  - name: app-config
    namespace: examai
    literals:
      - ASPNETCORE_ENVIRONMENT=Production
      - AWS_BUCKET_NAME=examai-production-files
      - RABBITMQ_CONNECTION_STRING=amqp://examai:prod_pass@rabbitmq-service:5672/

secretGenerator:
  - name: app-secrets
    namespace: examai
    literals:
      - DB_CONNECTION_STRING="Host=prod-db;Database=examai;Username=postgres;Password=VerySecretPassword"