apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: ocr-worker-scaler
  namespace: examai
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ocr-worker
  minReplicas: 2
  maxReplicas: 10
  cooldownPeriod: 300
  pollingInterval: 30
  triggers:
  - type: rabbitmq
    metadata:
      queueName: ocr-task-queue
      value: "5" # כמות הודעות ממוצעת לפוד שמפעילה שקפול
      hostFromEnv: RABBITMQ_CONNECTION_STRING