version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: examai_postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=examai
      - POSTGRES_PASSWORD=examai_local
      - POSTGRES_DB=examai
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2
    container_name: examai_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: examai_rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=examai
      - RABBITMQ_DEFAULT_PASS=examai_local
    volumes:
      - rabbit_data:/var/lib/rabbitmq

  minio:
    image: minio/minio
    container_name: examai_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=examai
      - MINIO_ROOT_PASSWORD=examai_local
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  elasticsearch:
    image: elasticsearch:8.11.1
    container_name: examai_elasticsearch
    ports:
      - "9200:9200"
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    volumes:
      - es_data:/usr/share/elasticsearch/data

  seq:
    image: datalust/seq:latest
    container_name: examai_seq
    ports:
      - "5341:5341"
    environment:
      - ACCEPT_EULA=Y
    volumes:
      - seq_data:/data

  clamav:
    image: clamav/clamav:latest
    container_name: examai_clamav
    ports:
      - "3310:3310"

volumes:
  pg_data:
  redis_data:
  rabbit_data:
  minio_data:
  es_data:
  seq_data: