apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - identity-api/deployment.yaml
  - identity-api/service.yaml
  - identity-api/hpa.yaml
  - ocr-worker/deployment.yaml
  - ocr-worker/keda-scaledobject.yaml