name: ExamAI CI

on:
  push:
    branches:
      - main
      - develop

jobs:
  frontend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        working-directory: src/examai-web
        run: npm install

      - name: Build Frontend
        working-directory: src/examai-web
        run: npm run build

  backend-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0

      - name: Restore
        run: dotnet restore src/backend

      - name: Build Backend
        run: dotnet build src/backend --configuration Release